language: 
  - java
  - ruby

jdk:
  - oraclejdk8

script: 
  - mvn clean install 
  - mvn test -B

# Use JDK 8u45. The above line just causes the use of a minor version of Java 8.
addons:
  apt:
    packages:
    - oracle-java8-installer

# safelist
branches:
  only:
  - master


