language: java

jdk:
  - oraclejdk8

script: ant build

# Use JDK 8u45. The above line just causes the use of a minor version of Java 8.
addons:
  apt:
    packages:
    - oracle-java8-installer

# safelist
branches:
  only:
  - master

before_install:
  - cd src\test\java\edu\usc\cs\group8\ImHungry

